/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fifa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Player_vs_player extends javax.swing.JFrame {

    /**
     * Creates new form Player_vs_player
     */
    public Player_vs_player() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public boolean verify_player1(String player1){
         
       PreparedStatement st;
        ResultSet rs;
        boolean player1_exist=false;
        String query ="Select* from users where username=?";
        try {
            st=My_Cnx.getConnection().prepareStatement(query);
            st.setString(1,player1);
            rs=st.executeQuery();
            if(!rs.next()){
                player1_exist=true;
                String[] options={"yes","no"};
                int  x=JOptionPane.showOptionDialog(null,"player 1 does not exist would you like to create a new player?","new player",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null, options,options[0]);
                if(x==0){
                    Register_Form form=new Register_Form();
                    form.setVisible(true);
                    form.pack();
                    form.setLocationRelativeTo(null);
                }else{
                    JOptionPane.showMessageDialog(null,"enter a valid username for player 1");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return player1_exist;
    }
     public boolean verify_player2(String player2){
         
       PreparedStatement st;
        ResultSet rs;
        boolean username_exist=false;
        String query ="Select* from users where username=?";
        try {
            st=My_Cnx.getConnection().prepareStatement(query);
            st.setString(1,player2);
            rs=st.executeQuery();
            if(!rs.next()){
                username_exist=true;
                 String[] options={"yes","no"};
                int  x=JOptionPane.showOptionDialog(null,"player 2 does not exist would you like to create a new player?","new player",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null, options,options[0]);
                if(x==0){
                    Register_Form form=new Register_Form();
                    form.setVisible(true);
                    form.pack();
                    form.setLocationRelativeTo(null);
                }else{
                    JOptionPane.showMessageDialog(null,"enter a valid username for player 2");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    public boolean compare(){
        String player1=jTextField_player1.getText();
        String player2=jTextField_player2.getText();
        
        if(player1.equals(player2)){
            JOptionPane.showMessageDialog(null,"Error player1 and player2 are the same person","Error",2);
            return true;
        }else{
            return false;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_team = new javax.swing.JLabel();
        jLabel_score = new javax.swing.JLabel();
        jTextField_team1 = new javax.swing.JTextField();
        jTextField_team2 = new javax.swing.JTextField();
        jTextField_score1 = new javax.swing.JTextField();
        jTextField_score2 = new javax.swing.JTextField();
        jButton_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel_team1 = new javax.swing.JLabel();
        jTextField_player1 = new javax.swing.JTextField();
        jTextField_player2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel_team.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_team.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_team.setText("TEAM");

        jLabel_score.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_score.setText("SCORE");

        jTextField_score1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_score1KeyTyped(evt);
            }
        });

        jTextField_score2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_score2KeyTyped(evt);
            }
        });

        jButton_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_submit.setText("SUBMIT");
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setText("REGULAR KICK OFF");

        jLabel_team1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_team1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_team1.setText("player");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_player1)
                    .addComponent(jTextField_player2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_team2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jTextField_team1))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_score1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_score2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel_team1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jLabel_team, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel_score, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_team)
                    .addComponent(jLabel_score)
                    .addComponent(jLabel_team1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_team1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_score1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_team2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_score2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton_submit)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        String player1=jTextField_player1.getText();
        String player2=jTextField_player2.getText();
        String team1=jTextField_team1.getText();
        String team2=jTextField_team2.getText();
        String score1=jTextField_score1.getText();
        String score2=jTextField_score2.getText();
        if(!verify_player1(player1)){
            if(!verify_player2(player2)){
                if(!compare()){
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery="insert into kick_off (player1,player2,team1,team2,score1,score2) values(?,?,?,?,?,?)";
                try {
                    ps=My_Cnx.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,player1);
                    ps.setString(2,player2);
                    ps.setString(3,team1);
                    ps.setString(4,team2);
                    ps.setString(5,score1);
                    ps.setString(6,score2);
                    if(ps.executeUpdate()!=0){
                         String[] options={"yes","no"};
       int  x=JOptionPane.showOptionDialog(null,"would you like to play another game","new kick off",JOptionPane.DEFAULT_OPTION,JOptionPane.INFORMATION_MESSAGE,null, options,options[0]);
       if(x==0){
           jTextField_player1.setText("");
            jTextField_player2.setText("");
             jTextField_team1.setText("");
              jTextField_team2.setText("");
               jTextField_score1.setText("");
                jTextField_score2.setText("");
       }
       else{
           this.dispose();
       }
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Player_vs_player.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            }
        }
    }//GEN-LAST:event_jButton_submitActionPerformed

    private void jTextField_score1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_score1KeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_score1KeyTyped

    private void jTextField_score2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_score2KeyTyped
       if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
       }
    }//GEN-LAST:event_jTextField_score2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player_vs_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player_vs_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player_vs_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player_vs_player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player_vs_player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_score;
    private javax.swing.JLabel jLabel_team;
    private javax.swing.JLabel jLabel_team1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_player1;
    private javax.swing.JTextField jTextField_player2;
    private javax.swing.JTextField jTextField_score1;
    private javax.swing.JTextField jTextField_score2;
    private javax.swing.JTextField jTextField_team1;
    private javax.swing.JTextField jTextField_team2;
    // End of variables declaration//GEN-END:variables
}
