/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fifa;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.border.Border;


/**
 *
 * @author lenovo
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    public Register_Form() {
        initComponents();
    }
    public boolean verifyFields(){
        String fname=jTextField_name.getText();
        String email=jTextField_email.getText();
        String username=jTextField_username.getText();
        String password=String.valueOf(jPasswordField.getPassword());
        String cpassword=String.valueOf(jPasswordField_c.getPassword());
        String fteam=jTextField_fteam.getText();
        String location=jTextField_location.getText();
        if(fname.trim().equals("") || email.trim().equals("") || username.trim().equals("") || password.trim().equals("") || cpassword.trim().equals("") || fteam.trim().equals("") || location.trim().equals("")){
            JOptionPane.showMessageDialog(null,"One or more fields are empty","error",2);
            return false;
        }
        //check if the two passwords are equal
        else if(!password.equals(cpassword)){
            JOptionPane.showMessageDialog(null,"Passwords don't match","confirm password",2);
            return false;
        }
        //if everything is ok
        else{
            return true;
        }
    }
    //create a function to check if the entered username already exists in the database
    public boolean checkUsername(String username){
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist=false;
        String query ="Select* from users where username=?";
        try {
            st=My_Cnx.getConnection().prepareStatement(query);
            st.setString(1,username);
            rs=st.executeQuery();
            if(rs.next()){
                username_exist=true;
                JOptionPane.showMessageDialog(null,"this user name already exists, choose another username","username failed",2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    public boolean nothingTyped(){
        String pass=String.valueOf(jPasswordField.getPassword());
        String cpass=String.valueOf(jPasswordField.getPassword());
         if(jTextField_name.getText().trim().equals("") || jTextField_name.getText().trim().toLowerCase().equals("full names")){
            jTextField_name.setText("");
            return true;
        }else if(jTextField_email.getText().trim().equals("") || jTextField_email.getText().trim().toLowerCase().equals("email or phone number")){
            jTextField_email.setText("");
            return true;
        }else if(jTextField_username.getText().trim().equals("") || jTextField_username.getText().trim().toLowerCase().equals("username")){
            jTextField_username.setText("");
            return true;
        }else if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            jPasswordField.setText("");
             return true;   
        }else if(cpass.trim().equals("") || cpass.trim().toLowerCase().equals("password")){
            jPasswordField.setText("");
             return true; 
        }else if(jTextField_fteam.getText().trim().equals("") || jTextField_fteam.getText().trim().toLowerCase().equals("favourite team")){
            jTextField_fteam.setText("");
            return true;
        }else if(jTextField_location.getText().trim().equals("") || jTextField_location.getText().trim().toLowerCase().equals("country of origin")){
            jTextField_location.setText("");
            return true;
        }else{
         return false;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_cpassword = new javax.swing.JLabel();
        jLabel_fteam = new javax.swing.JLabel();
        jLabel_location = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jTextField_fteam = new javax.swing.JTextField();
        jTextField_location = new javax.swing.JTextField();
        jButton_signup = new javax.swing.JButton();
        jLabel_login = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordField_c = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SIGN UP  FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name.setText("FULL NAME:");

        jLabel_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_email.setText("EMAIL/PHONE NUMBER:");

        jLabel_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_username.setText("USERNAME/NICKNAME:");

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_password.setText("PASSWORD:");

        jLabel_cpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cpassword.setText("CONFIRM PASSWORD:");

        jLabel_fteam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_fteam.setText("FAVOURITE TEAM:");

        jLabel_location.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_location.setText("LOCATION:");

        jTextField_email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_email.setText("email or phone number");
        jTextField_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailFocusLost(evt);
            }
        });

        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("username");
        jTextField_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_usernameFocusLost(evt);
            }
        });

        jTextField_fteam.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_fteam.setText("favourite team");
        jTextField_fteam.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_fteamFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_fteamFocusLost(evt);
            }
        });

        jTextField_location.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_location.setText("country of origin");
        jTextField_location.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_locationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_locationFocusLost(evt);
            }
        });

        jButton_signup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_signup.setText("SIGN UP");
        jButton_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_signupActionPerformed(evt);
            }
        });

        jLabel_login.setText("have an account? log in here.");
        jLabel_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_loginMouseExited(evt);
            }
        });

        jTextField_name.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_name.setText("full names");
        jTextField_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nameFocusLost(evt);
            }
        });
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyTyped(evt);
            }
        });

        jPasswordField.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField.setText("password");
        jPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldFocusLost(evt);
            }
        });

        jPasswordField_c.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_c.setText("confirm password");
        jPasswordField_c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_cFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_cFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_cpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_fteam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(jTextField_username)
                    .addComponent(jTextField_fteam)
                    .addComponent(jTextField_location)
                    .addComponent(jTextField_name)
                    .addComponent(jPasswordField)
                    .addComponent(jPasswordField_c))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_login, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_username, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fteam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fteam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_location, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_location, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jButton_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_login)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusLost
        if(jTextField_name.getText().trim().equals("") || jTextField_name.getText().trim().toLowerCase().equals("full names")){
            jTextField_name.setText("full names");
            jTextField_name.setForeground(Color.GRAY);
        }
        jLabel_name.setBorder(null);

    }//GEN-LAST:event_jTextField_nameFocusLost

    private void jTextField_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nameFocusGained
        if(jTextField_name.getText().trim().toLowerCase().equals("full names")){
            jTextField_name.setText("");
            jTextField_name.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        jLabel_name.setBorder(user);
    }//GEN-LAST:event_jTextField_nameFocusGained

    private void jLabel_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_loginMouseExited

    private void jLabel_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseEntered
        jLabel_login.setForeground(Color.blue);
    }//GEN-LAST:event_jLabel_loginMouseEntered

    private void jLabel_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_loginMouseClicked
        Login_form form=new Login_form();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_loginMouseClicked

    private void jTextField_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusGained
          if(jTextField_email.getText().trim().toLowerCase().equals("email or phone number")){
            jTextField_email.setText("");
            jTextField_email.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        jLabel_email.setBorder(user);
    }//GEN-LAST:event_jTextField_emailFocusGained

    private void jTextField_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailFocusLost
       if(jTextField_email.getText().trim().equals("") || jTextField_email.getText().trim().toLowerCase().equals("email or phone number")){
            jTextField_email.setText("email or phone number");
            jTextField_email.setForeground(Color.GRAY);
        }
        jLabel_email.setBorder(null);
    }//GEN-LAST:event_jTextField_emailFocusLost

    private void jTextField_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusGained
         if(jTextField_username.getText().trim().toLowerCase().equals("username")){
            jTextField_username.setText("");
            jTextField_username.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        jLabel_username.setBorder(user);
    }//GEN-LAST:event_jTextField_usernameFocusGained

    private void jTextField_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_usernameFocusLost
         if(jTextField_username.getText().trim().equals("") || jTextField_username.getText().trim().toLowerCase().equals("username")){
            jTextField_username.setText("username");
            jTextField_username.setForeground(Color.GRAY);
        }
        jLabel_username.setBorder(null);
    }//GEN-LAST:event_jTextField_usernameFocusLost

    private void jTextField_fteamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fteamFocusGained
         if(jTextField_fteam.getText().trim().toLowerCase().equals("favourite team")){
            jTextField_fteam.setText("");
            jTextField_fteam.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        jLabel_fteam.setBorder(user);
    }//GEN-LAST:event_jTextField_fteamFocusGained

    private void jTextField_fteamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_fteamFocusLost
        if(jTextField_fteam.getText().trim().equals("") || jTextField_fteam.getText().trim().toLowerCase().equals("favourite team")){
            jTextField_fteam.setText("favourite team");
            jTextField_fteam.setForeground(Color.GRAY);
        }
        jLabel_fteam.setBorder(null);
    }//GEN-LAST:event_jTextField_fteamFocusLost

    private void jTextField_locationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_locationFocusGained
         if(jTextField_location.getText().trim().toLowerCase().equals("country of origin")){
            jTextField_location.setText("");
            jTextField_location.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(3, 3, 3, 3, Color.GREEN);
        jLabel_location.setBorder(user);
    }//GEN-LAST:event_jTextField_locationFocusGained

    private void jTextField_locationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_locationFocusLost
         if(jTextField_location.getText().trim().equals("") || jTextField_location.getText().trim().toLowerCase().equals("country of origin")){
            jTextField_location.setText("country of origin");
            jTextField_location.setForeground(Color.GRAY);
        }
        jLabel_location.setBorder(null);
    }//GEN-LAST:event_jTextField_locationFocusLost

    private void jPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusGained
        String pass=String.valueOf(jPasswordField.getPassword());
        if(pass.trim().toLowerCase().equals("password")){
            jPasswordField.setText("");
            jPasswordField.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        jLabel_password.setBorder(user);
    }//GEN-LAST:event_jPasswordFieldFocusGained

    private void jPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldFocusLost
        String pass=String.valueOf(jPasswordField.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("password")){
            jPasswordField.setText("password");
             jPasswordField.setForeground(Color.GRAY);   
        }
        jLabel_password.setBorder(null);
    }//GEN-LAST:event_jPasswordFieldFocusLost

    private void jPasswordField_cFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_cFocusLost
         String pass=String.valueOf(jPasswordField_c.getPassword());
        if(pass.trim().equals("") || pass.trim().toLowerCase().equals("confirm password")){
            jPasswordField_c.setText("confirm password");
             jPasswordField_c.setForeground(Color.GRAY);   
        }
        jLabel_cpassword.setBorder(null);
    }//GEN-LAST:event_jPasswordField_cFocusLost

    private void jPasswordField_cFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_cFocusGained
         String pass=String.valueOf(jPasswordField_c.getPassword());
        if(pass.trim().toLowerCase().equals("confirm password")){
            jPasswordField_c.setText("");
            jPasswordField_c.setForeground(Color.BLACK);
        }
        Border user=BorderFactory.createMatteBorder(1, 1, 1, 1, Color.GREEN);
        jLabel_cpassword.setBorder(user);
    }//GEN-LAST:event_jPasswordField_cFocusGained

    private void jTextField_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyTyped
      //to allow only letters typed
      if(Character.isDigit(evt.getKeyChar())){
          evt.consume();
      }
    }//GEN-LAST:event_jTextField_nameKeyTyped

    private void jButton_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_signupActionPerformed
        String fname=jTextField_name.getText();
        String email=jTextField_email.getText();
        String username=jTextField_username.getText();
        String password=String.valueOf(jPasswordField.getPassword());
        String cpassword=String.valueOf(jPasswordField_c.getPassword());
        String fteam=jTextField_fteam.getText();
        String location=jTextField_location.getText();
        if(verifyFields()){
            if(!checkUsername(username)){
                if(!nothingTyped()){
                PreparedStatement ps;
                ResultSet rs;
                String registerUserQuery="insert into users (name,email,username,password,favourite_team,location) values(?,?,?,?,?,?)";
                try {
                    ps=My_Cnx.getConnection().prepareStatement(registerUserQuery);
                    ps.setString(1,fname);
                    ps.setString(2,email);
                    ps.setString(3,username);
                    ps.setString(4,password);
                    ps.setString(5,fteam);
                    ps.setString(6,location);
                    if(ps.executeUpdate()!=0){
                        JOptionPane.showMessageDialog(null,"account created successfully","success!",2);
                        Login_form log=new Login_form();
                        log.setVisible(true);
                        log.pack();
                        log.setLocationRelativeTo(null);
                        this.dispose();
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Error:check your details");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                }
                }
        }
    }//GEN-LAST:event_jButton_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_signup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_cpassword;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fteam;
    private javax.swing.JLabel jLabel_location;
    private javax.swing.JLabel jLabel_login;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField_c;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_fteam;
    private javax.swing.JTextField jTextField_location;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
